stages:
  - deploy

sftp-service:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: deploy
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"******\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_USER}" "${HARBOR_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "."      
      --dockerfile "Dockerfile"
      --build-arg TAG=${CI_COMMIT_TAG}
      --destination "****/****/sftp-service:${CI_COMMIT_TAG}"
  only:
    - tags